{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}
  labels:
{{ include "prometheus-exporter.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
