apiVersion: v1
name: finops-resources-exporter
version: 1.0.0
appVersion: 1.0.0
description: Finops Resources Chart Helm 
keywords:
- prometheus
- exporter
- finops
home: https://github.com/COPRS/monitoring/blob/main/finops/resources_exporter/helm
sources:
- https://github.com/COPRS/monitoring/blob/main/finops/resources_exporter
maintainers:
- name: CS Group
