name: Docker Trace Processor 

on:
  push:
    paths:
      - 'trace-processor/**'
      - '.github/workflows/docker-ci-traceprocessor.yml'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ secrets.CS_ARTIFACTORY_USER }}
  REGISTRY_PWD: ${{ secrets.CS_ARTIFACTORY_PASSWORD }}
  REGISTRY_BASE: artifactory.coprs.esa-copernicus.eu/rs-docker

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up env
        run: |
          # Artifactory
          echo "REGISTRY_USER=${{ env.REGISTRY_USER }}" >> $GITHUB_ENV
          echo "REGISTRY_PWD=${{ env.REGISTRY_PWD }}" >> $GITHUB_ENV
          echo "REGISTRY_BASE=${{ env.REGISTRY_BASE }}" >> $GITHUB_ENV
          # Git
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          GIT_TAG=${GITHUB_REF/refs\/tags\//}
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean deploy -Djib.dest-registry=${{ env.REGISTRY_BASE }} -Djib.dest-username=${{ env.REGISTRY_USER }} -Djib.dest-password="${{ env.REGISTRY_PWD }}" -Drevision=${{ env.GIT_TAG }} -f trace-processor
