name: Helm FINOPS

on:
  push:
    branches:
      - release/*
    paths:
      - 'finops/**'
      - '.github/workflows/helm-finops.yml'
  workflow_dispatch:

env:
  CHART_FOLDER: finops
  ARTIFACTORY_BASE_URL: "artifactory.coprs.esa-copernicus.eu"
  ARTIFACTORY_PROJECT: "cs-helm"
  USERNAME: ${{ secrets.CS_ARTIFACTORY_USER }}
  PASSWORD: ${{ secrets.CS_ARTIFACTORY_PASSWORD }}
  GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [object-storage-exporter, resources-exporter]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ env.GITGUARDIAN_API_KEY }}
          
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Lint helm 
        run: helm lint ${{ env.CHART_FOLDER }}/${{ matrix.component }}/helm/

      - name: Package helm
        run: helm package ${{ env.CHART_FOLDER }}/${{ matrix.component }}/helm/

      - name: Push to Artifactory
        run: curl -u "${{ env.USERNAME }}:${{ env.PASSWORD }}" -T *.tgz "https://artifactory.coprs.esa-copernicus.eu/artifactory/${{ env.ARTIFACTORY_PROJECT }}/${{ matrix.component }}.tgz"

