name: RS CORE Monitoring

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    paths:
      - 'rs-core/**'
      - '.github/workflows/rs-core.yml'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ secrets.CS_ARTIFACTORY_USER }}
  REGISTRY_PWD: ${{ secrets.CS_ARTIFACTORY_PASSWORD }}
  REGISTRY_BASE: artifactory.coprs.esa-copernicus.eu
  REGISTRY_PROJECT: rs-zip


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned

      - name: Build MONITORING
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: rs-cores/MONITORING/Release_Note.md
          output_dir: rs-cores/MONITORING/S2_L0U/
          table_of_contents: false
          # image_dir:
          build_html: false

      - name: Set environment variables
        run: |
          # Artifactory
          echo "REGISTRY_USER=${{ env.REGISTRY_USER }}" >> $GITHUB_ENV
          echo "REGISTRY_PWD=${{ env.REGISTRY_PWD }}" >> $GITHUB_ENV
          echo "REGISTRY_BASE=${{ env.REGISTRY_BASE }}" >> $GITHUB_ENV
          echo "REGISTRY_PROJECT=${{ env.REGISTRY_PROJECT }}" >> $GITHUB_ENV
          # Tag
          GIT_TAG=${GITHUB_REF/refs\/tags\//}
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

      - name: Build rs-cores and push
        run: |
          cd rs-cores
          ./build_cores.sh push
